#!/usr/bin/env python3
"""
Regenerate the LightTip launcher icon.

The mark is a percent sign: the tip on one tab, and on the other, two parties with a
line drawn between them. White line art on black, matching the icon language of the
sibling Light Phone III tools.

Geometry is defined once, in the 108x108 adaptive-icon canvas, and emitted twice —
as Android vector paths and as raster fallbacks. Everything sits inside the 18..90
safe zone so no launcher mask can clip it.

    python3 scripts/generate_icon.py

Needs Pillow. Rewrites app/src/main/res/{drawable,mipmap-*}.
"""

from __future__ import annotations

import os

from PIL import Image, ImageDraw

RES = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res")

CANVAS = 108
SAFE = (18, 90)
STROKE = 5.0
RING_R = 9.5  # centreline radius; outer edge lands at RING_R + STROKE/2
RING_A = (41.0, 41.0)
RING_B = (67.0, 67.0)
SLASH = ((73.0, 32.0), (35.0, 76.0))

DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
SUPERSAMPLE = 8


def check_safe_zone() -> None:
    lo, hi = SAFE
    edge = STROKE / 2
    extents = [
        (RING_A[0] - RING_R - edge, RING_A[1] - RING_R - edge),
        (RING_A[0] + RING_R + edge, RING_A[1] + RING_R + edge),
        (RING_B[0] - RING_R - edge, RING_B[1] - RING_R - edge),
        (RING_B[0] + RING_R + edge, RING_B[1] + RING_R + edge),
        (SLASH[0][0] + edge, SLASH[0][1] - edge),
        (SLASH[1][0] - edge, SLASH[1][1] + edge),
    ]
    for x, y in extents:
        assert lo <= x <= hi and lo <= y <= hi, f"({x}, {y}) escapes the safe zone"


def ring_path(cx: float, cy: float, r: float) -> str:
    return (
        f"M {cx - r},{cy} A {r},{r} 0 1 0 {cx + r},{cy} "
        f"A {r},{r} 0 1 0 {cx - r},{cy} Z"
    )


def write_vectors() -> None:
    background = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Pure black. On the Light Phone III's OLED these pixels are simply off. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{CANVAS}dp"
    android:height="{CANVAS}dp"
    android:viewportWidth="{CANVAS}"
    android:viewportHeight="{CANVAS}">
    <path
        android:fillColor="#000000"
        android:pathData="M0,0h{CANVAS}v{CANVAS}h-{CANVAS}z" />
</vector>
"""

    def stroked(path: str, filled_none: bool = True) -> str:
        fill = '\n        android:fillColor="#00000000"' if filled_none else ""
        return f"""    <path
        android:pathData="{path}"
        android:strokeColor="#FFFFFF"
        android:strokeWidth="{STROKE:g}"{fill}
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />"""

    (sx, sy), (ex, ey) = SLASH
    foreground = f"""<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by scripts/generate_icon.py — edit the geometry there, not here.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{CANVAS}dp"
    android:height="{CANVAS}dp"
    android:viewportWidth="{CANVAS}"
    android:viewportHeight="{CANVAS}">
{stroked(ring_path(*RING_A, RING_R))}
{stroked(ring_path(*RING_B, RING_R))}
{stroked(f"M {sx:g},{sy:g} L {ex:g},{ey:g}", filled_none=False)}
</vector>
"""

    adaptive = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
"""

    os.makedirs(os.path.join(RES, "drawable"), exist_ok=True)
    os.makedirs(os.path.join(RES, "mipmap-anydpi-v26"), exist_ok=True)
    with open(os.path.join(RES, "drawable", "ic_launcher_background.xml"), "w") as f:
        f.write(background)
    with open(os.path.join(RES, "drawable", "ic_launcher_foreground.xml"), "w") as f:
        f.write(foreground)
    for name in ("ic_launcher", "ic_launcher_round"):
        with open(os.path.join(RES, "mipmap-anydpi-v26", f"{name}.xml"), "w") as f:
            f.write(adaptive)


def render(px: int, circular: bool) -> Image.Image:
    s = SUPERSAMPLE
    img = Image.new("RGBA", (CANVAS * s, CANVAS * s), (0, 0, 0, 255))
    d = ImageDraw.Draw(img)
    w = STROKE * s

    def ring(cx: float, cy: float, r: float) -> None:
        d.ellipse(
            [(cx - r) * s - w / 2, (cy - r) * s - w / 2,
             (cx + r) * s + w / 2, (cy + r) * s + w / 2],
            fill=(255, 255, 255, 255),
        )
        d.ellipse(
            [(cx - r) * s + w / 2, (cy - r) * s + w / 2,
             (cx + r) * s - w / 2, (cy + r) * s - w / 2],
            fill=(0, 0, 0, 255),
        )

    ring(*RING_A, RING_R)
    ring(*RING_B, RING_R)
    (sx, sy), (ex, ey) = SLASH
    d.line([(sx * s, sy * s), (ex * s, ey * s)], fill=(255, 255, 255, 255), width=int(w))
    for x, y in (SLASH[0], SLASH[1]):  # round caps
        d.ellipse([x * s - w / 2, y * s - w / 2, x * s + w / 2, y * s + w / 2],
                  fill=(255, 255, 255, 255))

    # Crop to the 72x72 the launcher actually shows, so the legacy raster matches
    # what the adaptive icon looks like under a mask.
    lo, hi = SAFE
    out = img.crop((lo * s, lo * s, hi * s, hi * s)).resize((px, px), Image.LANCZOS)

    if circular:
        mask = Image.new("L", (px * 4, px * 4), 0)
        ImageDraw.Draw(mask).ellipse([0, 0, px * 4 - 1, px * 4 - 1], fill=255)
        mask = mask.resize((px, px), Image.LANCZOS)
        base = Image.new("RGBA", (px, px), (0, 0, 0, 0))
        base.paste(out, (0, 0), mask)
        out = base
    return out


def write_rasters() -> None:
    for dpi, px in DENSITIES.items():
        folder = os.path.join(RES, f"mipmap-{dpi}")
        os.makedirs(folder, exist_ok=True)
        render(px, False).save(os.path.join(folder, "ic_launcher.png"))
        render(px, True).save(os.path.join(folder, "ic_launcher_round.png"))


if __name__ == "__main__":
    check_safe_zone()
    write_vectors()
    write_rasters()
    print("icon regenerated in", os.path.normpath(RES))
